# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend-deployment
  labels:
    app: todo
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      tier: frontend
  template:
    metadata:
      labels:
        app: todo
        tier: frontend
    spec:
      containers:
        - name: todo-frontend
          image: "{{.Values.frontend.image}}:{{.Values.frontend.imageTag}}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
