# prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
  labels:
    app: todo
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      tier: backend
  template:
    metadata:
      labels:
        app: todo
        tier: backend
    spec:
      containers:
        - name: todo-backend
          image: "{{ .Values.backend.image }}:{{.Values.backend.imageTag}}"
          env:
            - name: DB_HOST
              value: {{ .Values.database.host }}
            - name: DB_USERNAME
              value: {{ .Values.database.username }}
            - name: DB_PASSWORD
              value: "{{ .Values.database.password }}"
            - name: ENVIRONMENT
              value: {{ .Values.database.environment }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
