name: Deploy to EC2 instances

on:
  push:
    branches: ['main']

jobs:
  build-and-push-to-ecr:
    name: Build Docker Image and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup aws ecr details
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login Into Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build And Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.REPO_NAME }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-ec2:
    name: Deploy to EC2 Instance
    needs: build-and-push-to-ecr
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: ${{ needs.build-and-push-to-ecr.outputs.ecr_registry }}
      ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
      INSTANCE_IDS: ${{ vars.INSTANCE_IDS }}
      IMAGE_TAG: latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy using SSM
        run: |
          echo "Deploying to instances: $INSTANCE_IDS"
          command_id=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids $INSTANCE_IDS \
            --comment "Pull and run Docker container" \
            --parameters commands='[
              "aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin $ECR_REGISTRY",
            ]' \
            --output text \
            --query "Command.CommandId")

          echo "Command ID: $command_id"

          aws ssm get-command-invocation \
          --command-id "$CMD_ID" \
          --instance-id "$ID" \
          --output text

          aws ssm wait command-executed \
          --command-id $command_id \
          --instance-id i-0365b78f5dc2fc512
